import type { NextPage } from 'next'
import Head from 'next/head'
import { DatePicker } from 'antd'
import Container from '@/components/Container'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container header={{ title: 'Home', subtitle: 'Home Page' }}>
        <main>
          <DatePicker />
        </main>
      </Container>

    </div>
  )
}

export default Home
